In [9]:
import numpy as np

In [144]:
def power_consumption(datafile):
    arr = []
    with open(datafile, 'r') as fp:
        for l in fp.readlines():
            row = np.array(list(l.strip()), dtype=int)
            arr.append(row)
    arr = np.array(arr)
    sbin = [np.bincount(arr[:, i]).argmax() for i in range(arr.shape[1])]
    inv_sbin = [np.bincount(arr[:, i]).argmin() for i in range(arr.shape[1])]
    gamma = int(bin(int(''.join(map(str, sbin)), 2)), 2)
    epsilon = int(bin(int(''.join(map(str, inv_sbin)), 2)), 2)
    consumption = gamma * epsilon
    return consumption

In [145]:
power_consumption("test.txt")

198

In [146]:
power_consumption("input.txt")

1458194

In [101]:
arr = []
with open("input.txt", 'r') as fp:
    for l in fp.readlines():
        row = np.array(list(l.strip()), dtype=int)
        arr.append(row)
arr = np.array(arr)

In [83]:
arr

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 0, 1, 1, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 1, 0, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0]])

In [134]:
g = [np.bincount(arr[:, i]).argmax() for i in range(arr.shape[1])]

In [135]:
e = [np.bincount(arr[:, i]).argmin() for i in range(arr.shape[1])]

In [136]:
g, e

([0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0], [1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1])

In [129]:
np.packbits(np.flip(g), bitorder='little').view(np.uint16)

array([394], dtype=uint16)

In [131]:
np.packbits(np.flip(e), bitorder='little').view(np.uint16)

array([3701], dtype=uint16)

In [137]:
bin(int(''.join(map(str, g)), 2))

'0b110001010'

In [141]:
int(bin(int(''.join(map(str, e)), 2)), 2)

3701