In [1]:
import numpy as np

In [88]:
def count_intersects(datafile):
    with open(datafile) as fp:
        kept = []
        for l in fp.readlines():
            left, right = l.split(' -> ')
            left_coo = [int(i) for i in left.split(',')]
            right_coo = [int(i) for i in right.strip().split(',')]
            #if left_coo[0] == right_coo[0] or left_coo[1] == right_coo[1]:
            kept.append((left_coo, right_coo))
    kept = np.array(kept)
    im = np.zeros((kept.max()+1, kept.max()+1))
    for k in kept:
        x = (k[0][1], k[1][1])
        if x[0] > x[1]:
            xrange = range(x[0], x[1]-1, -1)
        else:
            xrange = range(x[0], x[1]+1)
        
        y = (k[0][0], k[1][0])
        if y[0] > y[1]:
            yrange = range(y[0], y[1]-1, -1)
        else:
            yrange = range(y[0], y[1]+1)
        
        if len(xrange) == len(yrange):
            for xx, yy in zip(xrange, yrange):
                im[xx, yy] += 1
        else:
            for xx in xrange:
                for yy in yrange:
                    im[xx, yy] += 1
    
    print(im)
    n_intersects = np.where(im > 1)[0].shape[0]
    return n_intersects


In [90]:
count_intersects("input.txt")

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


22213